{"uuid":"6cda6511-67a2-42b7-872a-f9d7c9d5abba","historyId":"de1d7fd4aa544796f0cdd8dcd096b71e","fullName":"com.testcase.LoginCase.testLogin","labels":[{"name":"package","value":"com.testcase.LoginCase"},{"name":"testClass","value":"com.testcase.LoginCase"},{"name":"testMethod","value":"testLogin"},{"name":"parentSuite","value":"线上环境-自动化测试框架-mall项目-Demo"},{"name":"suite","value":"登录"},{"name":"subSuite","value":"com.testcase.LoginCase"},{"name":"host","value":"Athena"},{"name":"thread","value":"3068@Athena.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"用户模块"},{"name":"feature","value":"登录功能"}],"links":[],"name":"登录接口测试","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"写入 Excel 文件失败: src/test/resources/case_mall.xlsx","trace":"java.lang.RuntimeException: 写入 Excel 文件失败: src/test/resources/case_mall.xlsx\r\n\tat com.excelutils.BatchWriteToExcel.batchWriteToExcel(BatchWriteToExcel.java:58)\r\n\tat com.testcase.BaseCase.finishWriteBackAndAssert(BaseCase.java:165)\r\n\tat com.testcase.LoginCase.testLogin(LoginCase.java:44)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.io.FileNotFoundException: src\\test\\resources\\case_mall.xlsx (另一个程序正在使用此文件，进程无法访问。)\r\n\tat java.io.FileOutputStream.open0(Native Method)\r\n\tat java.io.FileOutputStream.open(FileOutputStream.java:270)\r\n\tat java.io.FileOutputStream.<init>(FileOutputStream.java:213)\r\n\tat java.io.FileOutputStream.<init>(FileOutputStream.java:101)\r\n\tat com.excelutils.BatchWriteToExcel.batchWriteToExcel(BatchWriteToExcel.java:51)\r\n\t... 29 more\r\n"},"stage":"finished","steps":[{"name":"【用例信息】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"用例信息明细","source":"dfb8ea21-4350-426c-a3f7-97f2d01cf5f2-attachment","type":"text/plain"}],"parameters":[],"start":1742983179167,"stop":1742983179168},{"name":"【发起请求】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"请求信息","source":"1f3e050e-20d9-4459-9d58-1c7b81bb0eed-attachment","type":"text/plain"}],"parameters":[],"start":1742983179168,"stop":1742983179215},{"name":"【响应断言】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"响应断言信息","source":"7f1ee500-1901-4cbd-a5b9-411269072212-attachment","type":"text/plain"}],"parameters":[],"start":1742983179216,"stop":1742983179217},{"name":"【数据库断言】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"数据库断言信息","source":"25e57e01-ed3d-4f8a-aa48-87f3073bd21d-attachment","type":"text/plain"}],"parameters":[],"start":1742983179281,"stop":1742983179283},{"name":"【最终测试结果】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"最终结果信息","source":"860d2acd-bd16-4067-a044-696d32f990b0-attachment","type":"text/plain"}],"parameters":[],"start":1742983179283,"stop":1742983179285}],"attachments":[],"parameters":[{"name":"arg0","value":"登录不成功：账号不正确"}],"start":1742983179075,"stop":1742983179337}