{"uuid":"cee9adb3-b701-4f7d-b22a-743358ad08b4","name":"线上环境-自动化测试框架-mall项目-Demo","children":["0cd4b5be-a3f0-493a-8409-c843256d23c1","ee43ad34-c169-4f36-94a5-e08cca103bd6"],"befores":[{"name":"setup","status":"passed","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1743221963122,"stop":1743221963128}],"afters":[{"name":"tearDown","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"写入 Excel 文件失败: src/test/resources/case_mall.xlsx","trace":"java.lang.RuntimeException: 写入 Excel 文件失败: src/test/resources/case_mall.xlsx\r\n\tat com.excelutils.BatchWriteToExcel.batchWriteToExcel(BatchWriteToExcel.java:90)\r\n\tat com.testcase.BaseCase.tearDown(BaseCase.java:94)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:369)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.io.FileNotFoundException: src\\test\\resources\\case_mall.xlsx (另一个程序正在使用此文件，进程无法访问。)\r\n\tat java.io.FileOutputStream.open0(Native Method)\r\n\tat java.io.FileOutputStream.open(FileOutputStream.java:270)\r\n\tat java.io.FileOutputStream.<init>(FileOutputStream.java:213)\r\n\tat java.io.FileOutputStream.<init>(FileOutputStream.java:101)\r\n\tat com.excelutils.BatchWriteToExcel.batchWriteToExcel(BatchWriteToExcel.java:80)\r\n\t... 19 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1743221966529,"stop":1743221966575}],"start":1743221963100,"stop":1743221966585}