{"uuid":"d660c781-7c36-47f7-9bee-ba1e578c71ac","historyId":"4eb3fd834e39bcd9e4f62c3131404d54","fullName":"com.testCase.LoginCase2.testLogin","labels":[{"name":"package","value":"com.testCase.LoginCase2"},{"name":"testClass","value":"com.testCase.LoginCase2"},{"name":"testMethod","value":"testLogin"},{"name":"parentSuite","value":"线上环境-自动化测试框架-mall项目-Demo"},{"name":"suite","value":"登录"},{"name":"subSuite","value":"com.testCase.LoginCase2"},{"name":"host","value":"Athena"},{"name":"thread","value":"13456@Athena.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"用户模块"},{"name":"feature","value":"登录功能"}],"links":[],"name":"登录接口测试","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"断言失败：响应断言=true，SQL断言=false did not expect to find [true] but found [false]","trace":"java.lang.AssertionError: 断言失败：响应断言=true，SQL断言=false did not expect to find [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:969)\r\n\tat org.testng.Assert.assertTrue(Assert.java:43)\r\n\tat com.testCase.LoginCase2.writeFinalTestResult(LoginCase2.java:144)\r\n\tat com.testCase.LoginCase2.testLogin(LoginCase2.java:58)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[{"name":"【用例信息】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"用例信息明细","source":"cce81dc7-e4da-440b-986f-686e43df1d2f-attachment","type":"text/plain"}],"parameters":[{"name":"caseInfo","value":"CaseInfo{caseId=2, caseDesc='登录不成功：账号不正确', url='\nhttp://129.28.122.208:8089/admin/login', contentType='json', type='post', params='{\"username\":\"testA\",\"password\":\"123456\"}', expectedResult='{\"code\":500,\"message\":\"登录异常:用户不存在\"}', sql='SELECT COUNT(*) \nFROM ums_admin_login_log l\nJOIN ums_admin a ON l.admin_id = a.id\nWHERE a.username = 'testA';\n'}"}],"start":1742801203169,"stop":1742801203169},{"name":"【发起请求】地址：\nhttp://129.28.122.208:8089/admin/login, 参数：{\"username\":\"testA\",\"password\":\"123456\"}, 方法：post","status":"passed","stage":"finished","steps":[{"name":"【响应结果】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"响应结果 JSON","source":"373d42ff-1820-4ba1-b477-855be3b42a60-attachment","type":"application/json"}],"parameters":[{"name":"responseResult","value":"{\"code\":500,\"message\":\"登录异常:用户不存在\",\"data\":null}"}],"start":1742801203220,"stop":1742801203221}],"attachments":[],"parameters":[{"name":"headers","value":"{content-type=application/json}"},{"name":"url","value":"\nhttp://129.28.122.208:8089/admin/login"},{"name":"params","value":"{\"username\":\"testA\",\"password\":\"123456\"}"},{"name":"type","value":"post"}],"start":1742801203178,"stop":1742801203221},{"name":"【响应断言】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"响应断言信息","source":"e34447b6-51a5-4501-9b08-7191ab14f6bc-attachment","type":"text/plain"}],"parameters":[{"name":"caseInfo","value":"CaseInfo{caseId=2, caseDesc='登录不成功：账号不正确', url='\nhttp://129.28.122.208:8089/admin/login', contentType='json', type='post', params='{\"username\":\"testA\",\"password\":\"123456\"}', expectedResult='{\"code\":500,\"message\":\"登录异常:用户不存在\"}', sql='SELECT COUNT(*) \nFROM ums_admin_login_log l\nJOIN ums_admin a ON l.admin_id = a.id\nWHERE a.username = 'testA';\n'}"},{"name":"response","value":"{\"code\":500,\"message\":\"登录异常:用户不存在\",\"data\":null}"}],"start":1742801203221,"stop":1742801203222},{"name":"【数据库查询与断言】SQL：SELECT COUNT(*) \nFROM ums_admin_login_log l\nJOIN ums_admin a ON l.admin_id = a.id\nWHERE a.username = 'testA';\n，请求前记录数：0，请求后记录数：0","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"sql","value":"SELECT COUNT(*) \nFROM ums_admin_login_log l\nJOIN ums_admin a ON l.admin_id = a.id\nWHERE a.username = 'testA';\n"},{"name":"before","value":"0"},{"name":"after","value":"0"}],"start":1742801203232,"stop":1742801203232},{"name":"【最终用例测试结果】是否通过：CaseInfo{caseId=2, caseDesc='登录不成功：账号不正确', url='\nhttp://129.28.122.208:8089/admin/login', contentType='json', type='post', params='{\"username\":\"testA\",\"password\":\"123456\"}', expectedResult='{\"code\":500,\"message\":\"登录异常:用户不存在\"}', sql='SELECT COUNT(*) \nFROM ums_admin_login_log l\nJOIN ums_admin a ON l.admin_id = a.id\nWHERE a.username = 'testA';\n'}，用例执行结果：true","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"断言失败：响应断言=true，SQL断言=false did not expect to find [true] but found [false]","trace":"java.lang.AssertionError: 断言失败：响应断言=true，SQL断言=false did not expect to find [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:969)\r\n\tat org.testng.Assert.assertTrue(Assert.java:43)\r\n\tat com.testCase.LoginCase2.writeFinalTestResult(LoginCase2.java:144)\r\n\tat com.testCase.LoginCase2.testLogin(LoginCase2.java:58)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"caseInfo","value":"CaseInfo{caseId=2, caseDesc='登录不成功：账号不正确', url='\nhttp://129.28.122.208:8089/admin/login', contentType='json', type='post', params='{\"username\":\"testA\",\"password\":\"123456\"}', expectedResult='{\"code\":500,\"message\":\"登录异常:用户不存在\"}', sql='SELECT COUNT(*) \nFROM ums_admin_login_log l\nJOIN ums_admin a ON l.admin_id = a.id\nWHERE a.username = 'testA';\n'}"},{"name":"assertResponse","value":"true"},{"name":"assertSQL","value":"false"}],"start":1742801203232,"stop":1742801203234}],"attachments":[],"parameters":[{"name":"arg0","value":"CaseInfo{caseId=2, caseDesc='登录不成功：账号不正确', url='\nhttp://129.28.122.208:8089/admin/login', contentType='json', type='post', params='{\"username\":\"${username2}\",\"password\":\"${password2}\"}', expectedResult='{\"code\":500,\"message\":\"登录异常:用户不存在\"}', sql='SELECT COUNT(*) \nFROM ums_admin_login_log l\nJOIN ums_admin a ON l.admin_id = a.id\nWHERE a.username = '${username2}';\n'}"}],"start":1742801203167,"stop":1742801203235}