{"uuid":"ff446f35-d420-4455-a998-d243293e714f","historyId":"5842e85675a6fc7b489e7f1966d7c2f1","fullName":"com.testcase.LoginCase.testLogin","labels":[{"name":"package","value":"com.testcase.LoginCase"},{"name":"testClass","value":"com.testcase.LoginCase"},{"name":"testMethod","value":"testLogin"},{"name":"parentSuite","value":"线上环境-自动化测试框架-mall项目-Demo"},{"name":"suite","value":"登录"},{"name":"subSuite","value":"com.testcase.LoginCase"},{"name":"host","value":"Athena"},{"name":"thread","value":"3068@Athena.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"用户模块"},{"name":"feature","value":"登录功能"}],"links":[],"name":"登录接口测试","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"写入 Excel 文件失败: src/test/resources/case_mall.xlsx","trace":"java.lang.RuntimeException: 写入 Excel 文件失败: src/test/resources/case_mall.xlsx\r\n\tat com.excelutils.BatchWriteToExcel.batchWriteToExcel(BatchWriteToExcel.java:58)\r\n\tat com.testcase.BaseCase.finishWriteBackAndAssert(BaseCase.java:165)\r\n\tat com.testcase.LoginCase.testLogin(LoginCase.java:44)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.io.FileNotFoundException: src\\test\\resources\\case_mall.xlsx (另一个程序正在使用此文件，进程无法访问。)\r\n\tat java.io.FileOutputStream.open0(Native Method)\r\n\tat java.io.FileOutputStream.open(FileOutputStream.java:270)\r\n\tat java.io.FileOutputStream.<init>(FileOutputStream.java:213)\r\n\tat java.io.FileOutputStream.<init>(FileOutputStream.java:101)\r\n\tat com.excelutils.BatchWriteToExcel.batchWriteToExcel(BatchWriteToExcel.java:51)\r\n\t... 29 more\r\n"},"stage":"finished","steps":[{"name":"【用例信息】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"用例信息明细","source":"4b535b77-c871-47bc-8468-669ac7925ae3-attachment","type":"text/plain"}],"parameters":[],"start":1742983179405,"stop":1742983179406},{"name":"【发起请求】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"请求信息","source":"73034c2b-0e33-467f-8224-06c78a8fdb87-attachment","type":"text/plain"}],"parameters":[],"start":1742983179406,"stop":1742983179542},{"name":"【响应断言】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"响应断言信息","source":"0e099c16-e92c-408d-ab14-ea23575258ec-attachment","type":"text/plain"}],"parameters":[],"start":1742983179542,"stop":1742983179544},{"name":"【数据库断言】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"数据库断言信息","source":"cbd4a019-69f4-4f3a-bc97-5e5ce6b03c27-attachment","type":"text/plain"}],"parameters":[],"start":1742983179614,"stop":1742983179616},{"name":"【最终测试结果】","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"最终结果信息","source":"54b9f153-bcc8-46d5-a212-24801a404069-attachment","type":"text/plain"}],"parameters":[],"start":1742983179616,"stop":1742983179617}],"attachments":[],"parameters":[{"name":"arg0","value":"登录不成功：密码不正确"}],"start":1742983179342,"stop":1742983179659}